title: React Children Utilities
description: Extended utils for React.Children opaque data structure.

main_nav:
  - title: Getting Started
    url: /getting-started
  - title: API
    url: /api

content_table:
  - title: Getting Started
    url: /getting-started
  - title: API
    url: /api
    links:
      - title: deepFilter
        url: /deep-filter
      - title: deepFind
        url: /deep-find
      - title: deepForEach
        url: /deep-foreach
      - title: deepMap
        url: /deep-map
      - title: filter
        url: /filter
      - title: groupByType
        url: /group-by-type
      - title: hasChildren
        url: /has-children
      - title: hasComplexChildren
        url: /has-complex-children
      - title: onlyText
        url: /only-text

google_analytics: UA-5425682-4

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
